// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX8Nsl2j7F5GGcKI1rnVmnRpsEiW70wkU',
    appId: '1:192007880090:web:bd5650ebafc7a2bc53ce23',
    messagingSenderId: '192007880090',
    projectId: 'book-tracker-602ee',
    authDomain: 'book-tracker-602ee.firebaseapp.com',
    storageBucket: 'book-tracker-602ee.firebasestorage.app',
    measurementId: 'G-BZX937KZ6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7127vvrg-JvK-zrHfSMO5nOEPg4_gMsI',
    appId: '1:192007880090:android:4c2d40a82cf7938053ce23',
    messagingSenderId: '192007880090',
    projectId: 'book-tracker-602ee',
    storageBucket: 'book-tracker-602ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtX-e3bD01BpdlM_CnpI9D3YSvVEuG6wY',
    appId: '1:192007880090:ios:d8a7ad564b3f764753ce23',
    messagingSenderId: '192007880090',
    projectId: 'book-tracker-602ee',
    storageBucket: 'book-tracker-602ee.firebasestorage.app',
    iosBundleId: 'com.example.bookTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtX-e3bD01BpdlM_CnpI9D3YSvVEuG6wY',
    appId: '1:192007880090:ios:d8a7ad564b3f764753ce23',
    messagingSenderId: '192007880090',
    projectId: 'book-tracker-602ee',
    storageBucket: 'book-tracker-602ee.firebasestorage.app',
    iosBundleId: 'com.example.bookTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX8Nsl2j7F5GGcKI1rnVmnRpsEiW70wkU',
    appId: '1:192007880090:web:6c48dba543fbfa8253ce23',
    messagingSenderId: '192007880090',
    projectId: 'book-tracker-602ee',
    authDomain: 'book-tracker-602ee.firebaseapp.com',
    storageBucket: 'book-tracker-602ee.firebasestorage.app',
    measurementId: 'G-S70678M5SF',
  );

}